CREATE OR REPLACE TRIGGER TR_B_IU_CLIENTE 
BEFORE INSERT OR UPDATE OF TIPO_VIAJE 
ON CLIENTE 
FOR EACH ROW
WHEN (new.TIPO_VIAJE <> 'TURISTICO' AND new.TIPO_VIAJE <> 'RESIDENCIA')
BEGIN
   RAISE_APPLICATION_ERROR(-20002,'VALOR NO ADMITIDO: '||TO_CHAR(:new.TIPO_VIAJE));
END;