CREATE OR REPLACE TRIGGER TR_B_AUDITORIA 
BEFORE DELETE OR UPDATE OR INSERT 
ON CLIENTE 

BEGIN
  IF INSERTING THEN
    INSERT INTO AUDITORIA VALUES(user,'Insertando',sysdate);
  END IF;
  IF DELETING THEN
    INSERT INTO AUDITORIA VALUES(user,'Eliminando',sysdate);
  END IF;
  IF UPDATING THEN
    INSERT INTO AUDITORIA VALUES(user,'Modificando',sysdate);
  END IF;
END;
