create or replace TRIGGER TR_B_IU_CLIENTE 
BEFORE INSERT OR UPDATE OF TIPO_VIAJE ON CLIENTE 
FOR EACH ROW
DECLARE
  VIAJE_NO_VALIDO EXCEPTION;
BEGIN
  IF :new.TIPO_VIAJE <> 'TURISTICO' AND :new.TIPO_VIAJE <> 'RESIDENCIA' THEN
     RAISE VIAJE_NO_VALIDO;
  END IF;
EXCEPTION
 WHEN VIAJE_NO_VALIDO THEN
  RAISE_APPLICATION_ERROR(-20002,'VALOR NO ADMITIDO: '||TO_CHAR(:new.TIPO_VIAJE));
END;
